### PR TITLE
Improve testing

### LINKED ISSUE #7: writing tests and running them with travis CI
I think that the codebase of npy-matlab could be improved in terms of testing.

1. first we could organize the repo and separate the following files into separate directories
    - examples (e.g., `exampleMemmap.m`, ...)
    - tests and test data (e.g., `test_readNPY.m`, `data`, ...)
    - the actual code (e.g., `writeNPY.m`, ...)

2. Then, we could write some automated tests that can be run automatically in octave using Tavis-CI
    - for an initial start, see a branch in my fork: https://github.com/sappelhoff/npy-matlab/blob/improve_testing/.travis.yml
    - possible testing framework: https://github.com/MOxUnit/MOxUnit

3. Eventually and once the new tests are in place, we could get rid of the `data` directory and the `npy.ipynb` file and all other files and data that are currently in place for some "manual testing". The automated testing that we would establish could then generate the data on the fly while being run on a Travis CI server

All in all, these would be good steps to move the "experimental code" (as you write in the github description) towards a more stable and tested code.

What are your opinions on this?

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #7 

This PR involves some major restructuring, but the basic functionality is completely preserved. The biggest changes I made are listed below:

1. organize the files into `npy-matlab`, `tests`, and `examples` directories
2. extensively update the README information
3. In the LICENSE, I changed the copyright holder from "kwik team" to "npy-matlab developers". Let me know if you are not okay with that.
4. Most importantly, I wrote ` tests/test_npy_roundtrip.py` which in conjunction with the added `.travis.yml` file will run a roundtrip testing procedure whenever a new code is added to this project
    - numpy write data (same testing data as before)
    - octave read data (we cannot use matlab itself unfortunately)
    - octave write data
    - numpy read back octave-written data and make sure it is the same as originally

Let me know what you think about these changes.

For the roundtrip testing procedure to work automatically, you would have to create a Travis CI account with this Github account (Kwik Team) and then add the `npy-matlab` repository to the Travis CI. See https://docs.travis-ci.com/user/tutorial/ for more information.

### CODE REVIEW

**Comment by sappelhoff** [comment]
@nsteinme @rossant do you have time for a review?

**Comment by rossant** [comment]
I just activated travis. Trying to force the build -- I need to close and reopen...

**Comment by rossant** [comment]
many thanks for this @sappelhoff !
Travis passes. Looks good to me, I don't have any particular comments.
I don't have matlab, @nsteinme could you try it on your computer and let me know if it still works (notably the examples)?

**Comment by nsteinme** [comment]
There were no changes to the code, were there? Except a couple white space additions/deletions? If there were please point me to them? Otherwise I will just merge.

**Comment by sappelhoff** [comment]
yep, no code changes, +1 for merge

**Comment by rossant** [comment]
no changes to the code, just some files have been moved, and the tests, which work!
+1 for merge as well

**Comment by nsteinme** [comment]
thanks both!

**Pull request merged**
